# 编译配置文件
[compiler]
name     = "gf01" #编译后的文件名称
version  = "1.0.0" #编译后的文件会生成到/bin/1.0.0目录里
arch     = "386,amd64"
system   = "windows,darwin"
output   = ""
path     = "./bin"  #输出到bin目录
extra    = "-ldflags \"-s -w\""

# Database.
[database]
    link  = "mysql:dev_root:123456@tcp(10.176.124.106:33066)/iot_smarthome"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "D:/Users/Desktop/go/golearning/sql"
        Level  = "all"
        Stdout = true